AuthSessionMissingError: Auth session missing!     at https://6000-firebase-studio-1747079431072.cluster-3gc7bglotjgwuxlqpiut7yyqt4.cloudworkstations.dev/_next/static/chunks/node_modules_aca5f2ce._.js:16367:27     at SupabaseAuthClient._useSession (https://6000-firebase-studio-1747079431072.cluster-3gc7bglotjgwuxlqpiut7yyqt4.cloudworkstations.dev/_next/static/chunks/node_modules_aca5f2ce._.js:16204:26)     at async SupabaseAuthClient._updateUser (https://6000-firebase-studio-1747079431072.cluster-3gc7bglotjgwuxlqpiut7yyqt4.cloudworkstations.dev/_next/static/chunks/node_modules_aca5f2ce._.js:16361:20)     at async https://6000-firebase-studio-1747079431072.cluster-3gc7bglotjgwuxlqpiut7yyqt4.cloudworkstations.dev/_next/static/chunks/node_modules_aca5f2ce._.js:16356:20